include: package:flutter_lints/flutter.yaml

linter:
  rules:
    constant_identifier_names: true
    always_use_package_imports: true
    use_late_for_private_fields_and_variables: true
    unnecessary_late: true
    require_trailing_commas: true
    prefer_const_constructors: true
    prefer_const_declarations: true
    avoid_slow_async_io: true
    valid_regexps: true
    use_super_parameters: false
    prefer_foreach: false
    prefer_final_in_for_each: true