name: jima
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.6.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  vanilla_state: ^1.1.0+1
  equatable: ^2.0.7
  dio: ^5.8.0+1
  pretty_dio_logger: ^1.4.0
  logger: ^2.5.0
  go_router: ^14.8.1
  hive_flutter: ^1.1.0
  cached_network_image: ^3.4.1
  intl: ^0.20.2
  file_picker: ^10.0.0
  flutter_screenutil: ^5.9.3
  mask_text_input_formatter: ^2.9.0
  shimmer: ^3.0.0
  flutter_secure_storage: ^9.2.4
  uuid: ^4.5.1
  google_fonts: ^6.2.1
  get_it: ^8.0.3
  path_provider: ^2.1.5
  flutter_dotenv: ^5.2.1
  supabase_flutter: ^2.8.4
  sliver_tools: ^0.2.12
  flutter_svg: ^2.0.17
  toastification: ^3.0.2
  google_sign_in: ^6.3.0
  flutter_facebook_auth: ^7.1.1
  webview_flutter: ^4.10.0
  youtube_player_flutter: ^9.1.1
  url_launcher: ^6.3.1
  pinput: ^5.0.1
  files_uploader: ^0.1.1
  just_audio: ^0.10.2
  audio_session: ^0.2.1
  audio_service: ^0.18.18
  rxdart: ^0.28.0
  audiotags: ^1.4.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0


flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/vectors/
    - assets/env/